name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main


jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install requirements
        run: uv sync --frozen --dev --no-cache

      - name: Run unit tests
        run: uv run pytest tests/unit_tests/



